language: node_js
sudo: required
node_js:
  - 7
branches:
  only:
    - develop
install:
  - sudo apt-get install openjdk-8-jdk
  - sudo apt-get install ruby-full
  - gem update --system
  - gem install compass
  - npm install -g grunt-cli
  - npm install -g bower
before_script:
  - npm install
  - bower install
script: grunt build
