language: node_js
node_js:
- node
sudo: required
services:
- docker
cache:
  directories:
  - node_modules
branches:
  only:
  - develop
  - master
install:
- sudo apt-get install openjdk-8-jdk
- sudo apt-get install ruby-full
- gem update --system
- gem install compass
- npm install -g grunt-cli
- npm install -g bower
before_script:
- npm install
- bower install
script:
- grunt build
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- docker build -t $REPO:$TAG ./docker
after_success:
- cd docker
- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:$TRAVIS_BUILD_NUMBER
- docker push $REPO
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=jluccisano/nextrun
  - secure: jQuHvuSxN0bxg330CWoWtiK1Iyi7IPzKb12J+pAB4jCOATBV2nVVqs4bSz3Lzs8796/+iOpdqGBebI9VwoFT4zj9cDAkBZsPxMf/bmww8AVNHfbjjoGaiafezNDU5Ct1vTxc5KgYIMGkp/Ptsb9jDsibeUabi2a6PQQxv6qAqt1Fm4KZdlt9k6YFlHVdyA6xZL7eAyVwdghxJZB3XOErHtq3Nr10kYJ+cviaimTO2/3roIqMrtZKKKqpxoIZTm3ASyxuc2CmdV4pDZKAnSIG6HpohKoT+n/IvdZ51xO29zeEitcU8n1dZdzo7xwSfcdR8+4eUZgbAAUb3d8E8kkRJEy4xbYRkToVoIBcMaZmwzv64XaNMMbjjqoGCIZm2EhNr/+A0pPcTIxhuLMGli+JBSNoRx/gKWGZ1oWgb/gSbgiJjgctIIAjP201V7lRdM8bKTAU5ySHiiZU3P647b5Aro8j6oFWoEsQP4BI7V48ICibtXHeiXE4QpcDZJQKXqcQq9CaWGritCcw2UuUh9mQGuNAnYdJ0fRQY57mQNp9vxCZxTB4SxqYGM8BicP+rj8vykJaRb2wvigIE+35IOLv/RJBGzXxQJ4QzyiphKcFFbwIO8AVB0DZ7Yfh/cELm67SaI8StQJ0oeN+GSQBbzHuC5mTesRonUbMsc+BA+DqQT0=
  - secure: JVxqoG7WJ/bUo/fgJR95nv4hL8rxtZZCSpht0Q/4V0WkNfssA0nmWk4hIsuwSyLn7KzkncdYNAPRSlAuAxK34MP8MM3cB5qPLxSVLWVNkCBhWmOdswkBmJMwVWTA291xl8WVduSyeMx5jy0YN1RWKI+vupVafVhTnAei4sfD22pir2YCPi+eatP1QphAbrR77Zc/Eg1FTrX7+vZAH5HVJ+ySPHdhGj7FZ1n6TbEXGYoAF6H5IoT1r6XS2D/IG2HEeg5WHNvTi38C8PNPm/9gJx87W9zHWcFvdhlRLbXbA4bg5iyL6Fzz0vKhfLovDFJS6r9ba/MNG+qnW+ROmjeHZ7kVuQBxVZwopqwcuXIvdcZBdY8Uo1GS+oAQUP20d4hadv6jWV9MPsjmOqALorvJCaYLrfUSNgrcaoSYgUGSofWApaC/yQ59HUFF7zFjyk99DllRbdEtIx896PZscf7ljykVAroaF5W8tKAy2LaY3Eut2LYJ735xmDq1eEek7nTQPjYj3kCSl3/gjSngS/saW+6x1yYWkV2roOlUFfqouSpXQwrQg7gsJyotGcEsSIUfrPbKn6NQgYb+XPUi8tAxCfR3crMtLXfZY3//nJuoKRvZv0X5flqIRC5cKefZPILm9j1Lbcq4lsW5vr8Ni8zUbc48BN4nz2UUBTl/XOYxTFo=
